### ISSUE TITLE
Map opacity issue

### ISSUE THREAD

**Issue by razvanmierla** [leatrix/leatrix-maps-bcc#19]
Found one issue (I'm not sure if this is intended or not): observed the fact that if you're moving, opening the map & hovering over the map (without stopping from moving) the map remains with the "Moving" opacity. If you're stopping and start moving again, it works fine.

I could reproduce this issue as of version 2.5.38.
Uploaded a video on YouTube aswell for replication steps (as I can upload only 10 MBs of files in GitHub): https://www.youtube.com/watch?v=O_S64X7DKY4

**Comment by razvanmierla** [comment]
Yeah, disabling all the other addons solved it, tried to clear cache aswell and with other combinations of addon. It seems that other addons that modify the map causes issues. The problematic one that conflicted with Leatrix Maps was TomCat's AddOn Suite.

**Comment by leatrix** [comment]
TomCat's Addon Suite for BCC changes the map significantly.  As well as the map opacity issue (which is caused by TomCat applying its own map opacity), it also causes the points of interest icons (such as dungeons and flight points) in LTM to be much larger than intended.  However, TomCat's Addon Suite for BCC doesn't appear to have any configuration options so you cannot disable features that aren't needed.

If you really want to use TomCat, disable 'Set map opacity' in LTM and let TomCat fade the map.

**Comment by razvanmierla** [comment]
That's good to know, thanks for the help and sorry for opening an issue without more investigations. 

Have a nice day! :D
