### ISSUE TITLE
Questie POIs are outside the map frame

### ISSUE THREAD

**Issue by Rumchiller** [leatrix/leatrix-maps-bcc#42]
The POIs are outside the map frame. Not sure, if this is an issue with Questie or ltm. Tested with 2.5.63 and 2.5.64.alpha and Questie 6.6.4.

![zoom-less](https://user-images.githubusercontent.com/14004768/139546232-207e2745-d937-48dd-8c9a-6d4832976242.png)
![zoom-more](https://user-images.githubusercontent.com/14004768/139546265-d6a64774-9ddb-4ad7-ac49-c93f4efc0d2d.png)

**Comment by leatrix** [comment]
Questie has a known issue with map zoom.  You should ask the author of Questie about it.  It was reported a long time ago but the problem still exists.  It's not caused by Leatrix Maps specifically - Questie icons break with any addon that features map zoom.

I'm not aware of any issues with other addons that add icons to the map - HandyNotes, Gathermate 2, ClassicCodex, TomCatTours, Zygor, Leatrix Maps, Blizzard map icons - all work fine with map zoom.

A sort-of workaround for now is to run a macro like this when the icons break:

`/run local a = WorldMapFrame:GetMapID(); if a then WorldMapFrame:SetMapID(1415); WorldMapFrame:SetMapID(a) end`

It will refresh the map which fixes the icons that have already loaded temporarily.  The problem will slowly creep back as Questie adds icons to the map though.  If you open the map straight away after logging in, you'll need to wait for Questie to finish populating the map with icons before you run the macro.  Toggling the 'Show/Hide Questie' button on the world map can cause some icons to break too.

**Comment by leatrix** [comment]
This is from 6th September 2021
https://github.com/Questie/Questie/issues/3147
