### ISSUE TITLE
Some new FP markers disappear

### ISSUE THREAD

**Issue by boktai1000** [leatrix/leatrix-maps-bcc#9]
I was looking through the world map after logging into pre-patch and noticed several things like the new FP in Ashenvale/etc

But for whatever reason later, I noticed that some (but not all) of these FPs just mysteriously vanished.

Also some FP markers are golden (Mudsprocket) and some are blue - not sure what that means.

Either way, some markers were definitely there, but vanished - and some new ones are there for sure (Rebel Camp, Exodar, etc) but then some like South Felwood and Ashenvale's new one aren't there.

**Comment by leatrix** [comment]
Thanks for your ticket.

Emerald Sanctuary was missing and has been added in 2.5.33.alpha.3.
https://www.curseforge.com/wow/addons/leatrix-maps-bcc/files/all

Blue flight points are for Alliance.  Red ones are for Horde.  Yellow ones are neutral (either faction can use them).  Shadowlands uses the same system.

Disappearing flight points is probably caused by a conflict with another addon.  Disable other addons to see if the issue persists.  If it does not, enable other addons gradually to find the cause.

You said that an Ashenvale flight point is missing.  Is this a new flight point that's not in LTM or is it one of the disappearing flight points?

**Comment by leatrix** [comment]
Added Forest Song flight point (Alliance) to Ashenvale in 2.5.33.alpha.5.
https://github.com/leatrix/leatrix-maps-bcc/issues/11
